// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.InteropServices

[<assembly: AssemblyTitleAttribute("FSecurity.FsCheck")>]
[<assembly: AssemblyDescriptionAttribute("FSecuriy is a tool for automatically running security tests for .NET programs")>]
[<assembly: GuidAttribute("871111ca-f7e3-48c5-95b1-6eec4c289950")>]
[<assembly: AssemblyProductAttribute("FSecurity.FsCheck")>]
[<assembly: AssemblyVersionAttribute("2.1.0")>]
[<assembly: AssemblyFileVersionAttribute("2.1.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSecurity.FsCheck"
    let [<Literal>] AssemblyDescription = "FSecuriy is a tool for automatically running security tests for .NET programs"
    let [<Literal>] Guid = "871111ca-f7e3-48c5-95b1-6eec4c289950"
    let [<Literal>] AssemblyProduct = "FSecurity.FsCheck"
    let [<Literal>] AssemblyVersion = "2.1.0"
    let [<Literal>] AssemblyFileVersion = "2.1.0"
