// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FSec")>]
[<assembly: AssemblyProductAttribute("FSec")>]
[<assembly: AssemblyDescriptionAttribute("FSec is a tool for automatically running security tests for .NET programs")>]
[<assembly: AssemblyVersionAttribute("1.0.7")>]
[<assembly: AssemblyFileVersionAttribute("1.0.7")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSec"
    let [<Literal>] AssemblyProduct = "FSec"
    let [<Literal>] AssemblyDescription = "FSec is a tool for automatically running security tests for .NET programs"
    let [<Literal>] AssemblyVersion = "1.0.7"
    let [<Literal>] AssemblyFileVersion = "1.0.7"
    let [<Literal>] AssemblyConfiguration = "Release"
